### ISSUE TITLE
wish: [~chriskohlhoff/asio] aka `std::asio`

### ISSUE THREAD

**Issue by magenbluten** [magenbluten/build2-wishlist#12]
[~chriskohlhoff/asio](https://github.com/chriskohlhoff/asio)

**Comment by boris-kolpackov** [comment]
The version that is part of the Boost libraries is now available on cppget.org. For details, see: https://build2.org/blog/build2-boost.xhtml

**Comment by boris-kolpackov** [comment]
Standalone ASIO is now on cppget.org: https://cppget.org/libasio

So I am going to close this issue.
