### ISSUE TITLE
wish : crashpad

### ISSUE THREAD

**Issue by EmilRosenquist** [magenbluten/build2-wishlist#16]
crashpad: Crash-reporting system (he successor to breakpad). [github repo](https://github.com/chromium/crashpad).

**Comment by EmilRosenquist** [comment]
Work has started on mini_chromium which is the big blocking dependency here. 
See ongoing work https://github.com/build2-packaging/mini_chromium

**Comment by EmilRosenquist** [comment]
Another dependency of crashpad has been put up and is waiting for review https://github.com/build2-packaging/cpp-httplib

**Comment by EmilRosenquist** [comment]
Crashpad has been "alpha released" on queue.stage.build2.org https://queue.stage.build2.org/?packages=crashpad

**Comment by boris-kolpackov** [comment]
Crashpad is now on cppget.org so I am going to close this issue.
