### ISSUE TITLE
wish: cli11

### ISSUE THREAD

**Issue by EmilRosenquist** [magenbluten/build2-wishlist#21]
cli11: a command line parser for C++11 and beyond that provides a rich feature set with a simple and intuitive interface. https://github.com/CLIUtils/CLI11

**Comment by Klaim** [comment]
Hi! There is a package in progress there: https://github.com/build2-packaging/cli11
But it needs to be fixed before publication on cppget

**Comment by EmilRosenquist** [comment]
Continued the work since it had been stale for quite a while, 
https://github.com/build2-packaging/cli11/pull/4

**Comment by EmilRosenquist** [comment]
It has now been published and you can get it on cppget https://cppget.org/cli11?q=cli11
