### ISSUE TITLE
wish: flex

### ISSUE THREAD

**Issue by helmesjo** [magenbluten/build2-wishlist#23]
https://github.com/westes/flex
> flex is a tool for generating scanners: programs which recognize lexical patterns in text.

Should be implemented as a build system module if I understand the documentation correctly.

**Build prerequisites**
* m4 (https://github.com/build2-packaging/WISHLIST/issues/24)
* GNU bison (https://github.com/build2-packaging/WISHLIST/issues/22)

**Comment by boris-kolpackov** [comment]
There is already [`reflex`](https://cppget.org/reflex) which is reasonably-compatible with `flex`. See also a comment in #22 on potential difficulties with packaging `flex`.

**Comment by boris-kolpackov** [comment]
To clarify, there are no immediate plans to package GNU `flex` (due to the above-mentioned difficulties), but we would like to eventually, if we can.
