### ISSUE TITLE
wish: GNU M4

### ISSUE THREAD

**Issue by helmesjo** [magenbluten/build2-wishlist#24]
https://www.gnu.org/software/m4/
> GNU M4 is an implementation of the traditional Unix macro processor.

**Comment by boris-kolpackov** [comment]
There is already [`openbsd-m4`](https://cppget.org/openbsd-m4) which is reasonably-compatible with GNU `m4`.

**Comment by boris-kolpackov** [comment]
To clarify, there are no immediate plans to package GNU `flex` (due to difficulties), but we would like to eventually, if we can.
