### ISSUE TITLE
wish: thrift

### ISSUE THREAD

**Issue by helmesjo** [magenbluten/build2-wishlist#25]
https://github.com/apache/thrift
> Thrift is a lightweight, language-independent software stack for point-to-point RPC implementation. 

[**Build prerequisites**](https://github.com/apache/thrift/blob/master/doc/install/README.md#requirements-for-building-from-source)
* flex and bison - **Can possibly be replaced with byacc & reflex (already available as build2** packages)
  - https://github.com/build2-packaging/WISHLIST/issues/22
  - https://github.com/build2-packaging/WISHLIST/issues/23
  - https://github.com/build2-packaging/WISHLIST/issues/26
* libssl-dev

**Comment by boris-kolpackov** [comment]
If `libssl-dev` means `libssl` from OpenSSL, then we have that: https://cppget.org/libssl

**Comment by helmesjo** [comment]
@boris-kolpackov I'd assume that it means the typical dev-package available for different distros (usually two packages exists, eg. one with binaries aka [libssl](https://packages.ubuntu.com/jammy/libssl3) and one dev with headers etc aka [libssl-dev](https://packages.ubuntu.com/jammy/libssl-dev)), but yeah maybe above mentioned package covers it, then that'd be great!

**Comment by boris-kolpackov** [comment]
If we are talking about `libssl-dev` from Debain/Ubuntu, then our `libssl` package is definitely the equivalent.

**Comment by EmilRosenquist** [comment]
thrift has been released in staged https://queue.stage.build2.org/?packages=thrift

**Comment by Klaim** [comment]
Wow that was probably not trivial at all, good work 👍🏽
