### ISSUE TITLE
wish: toml++

### ISSUE THREAD

**Issue by wroyca** [magenbluten/build2-wishlist#30]
[![banner](https://github.com/marzer/tomlplusplus/blob/master/docs/images/banner.png?raw=true)](https://marzer.github.io/tomlplusplus/)

## Library features

- Header-only (optional!)
- Supports the latest [TOML] release ([v1.0.0]), plus optional support for some unreleased TOML features
- Passes all tests in the [toml-test](https://github.com/BurntSushi/toml-test) suite
- Supports serializing to JSON and YAML
- Proper UTF-8 handling (incl. BOM)
- C++17 (plus some C++20 features where available, e.g. experimental support for [char8_t] strings)
- Doesn't require RTTI
- Works with or without exceptions
- Tested on Clang (6+), GCC (7+) and MSVC (VS2019)
- Tested on x64, x86 and ARM
<br>

## Basic usage

> ℹ&#xFE0F; _The following example favours brevity. If you'd prefer full API documentation and lots of specific code snippets
instead, visit the project [homepage](https://marzer.github.io/tomlplusplus/)_

Given a TOML file `configuration.toml` containing the following:

```toml
[library]
name = "toml++"
authors = ["Mark Gillard <mark.gillard@outlook.com.au>"]

[dependencies]
cpp = 17
```

Reading it in C++ is easy with toml++:

```cpp
#include <toml.hpp>

auto config = toml::parse_file( "configuration.toml" );

// get key-value pairs
std::string_view library_name = config["library"]["name"].value_or(""sv);
std::string_view library_author = config["library"]["authors"][0].value_or(""sv);
int64_t depends_on_cpp_version = config["dependencies"]["cpp"].value_or(0);

// modify the data
config.insert_or_assign("alternatives", toml::array{
    "cpptoml",
    "toml11",
    "Boost.TOML"
});

// use a visitor to iterate over heterogenous data
config.for_each ([](auto& key, auto& value)
{
    std::cout << value << "\n";
    if constexpr (toml::is_string<decltype(value)>)
        do_something_with_string_values(value);
});

// you can also iterate more 'traditionally' using a ranged-for
for (auto&& [k, v] : config)
{
    // ...
}

// re-serialize as TOML
std::cout << config << "\n";

// re-serialize as JSON
std::cout << toml::json_formatter{ config } << "\n";

// re-serialize as YAML
std::cout << toml::yaml_formatter{ config } << "\n";

```

You'll find some more code examples in the [`examples`](https://github.com/marzer/tomlplusplus/tree/master/examples) directory, and plenty more as part of the [API documentation](https://marzer.github.io/tomlplusplus/index.html#mainpage-api-documentation).

CC @marzer ☕

**Comment by boris-kolpackov** [comment]
FYI, we have https://queue.cppget.org/toml11 sitting in the queue but the packaging quality needs quite a bit of work. The package repository is here (for now): https://github.com/good770326/toml11-build2-package

**Comment by Rookfighter** [comment]
I wanted to look into packaging this library soonish. Still have some other packages to finish first. I'll keep you updated 👍

**Comment by marzer** [comment]
Oh cool, let me know if you need anything from me

**Comment by Rookfighter** [comment]
FYI @marzer and @wroyca
I have started working on this package here:

https://github.com/build2-packaging/tomlplusplus

**Comment by wroyca** [comment]
Now available on https://cppget.org/libtomlplusplus, thank @Rookfighter! :beers:

**Comment by marzer** [comment]
Anything special for me to do here if/when I publish a new TOML++ release?

**Comment by Rookfighter** [comment]
@marzer If you want that the tomlplusplus build2 package kind of stays up to date, then I guess its best if you post an issue on the package repo. At some point someone (maybe me) will pick the ticket up.
If you **really** want the package to stay up to date (in parallel with your repo), you can even post a PR for the package repo.
If you don't take any action, I guess the community will take care of updating the package to the latest version whenever someone needs / wants to use it.
@boris-kolpackov Anything to add or correct?

**Comment by boris-kolpackov** [comment]
> Anything to add or correct?

Nope, you've outlined the options pretty accurately. I guess the only option not mentioned would be to add `build2` support upstream but to get the separate tests package arrangement (which is desirable due to the dependency on `catch2`) some restructuring of upstream would be needed. So it's probably not worth the trouble just for keeping things up to date.
